before_install:
  - gem install bundler
language: ruby
rvm:
  - 3.1.3
before_script:
- pip install --user awscli
- rm -rf public
- bundle exec jekyll build
script:
- aws s3 sync public/ s3://gearsofgordon.com --acl public-read --delete
- aws cloudfront create-invalidation --distribution-id E2SWQIYYM18JR9 --paths '/*'
branches:
 only:
 - master