### your site title here

title: Gears of Gordon
description: Cloud Engineering | Gender Equity | Youth Sport

baseurl: /gearsofgordon/ #name of GitHub repository
url: https://gearsofgordon.com #custom url to be used instead of GitHub repository
email: ggu9d2hlo@mozmail.com

# Pagination
paginate: 2
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: https://linkedin.com/in/gordongeringas
github: https://github.com/GordonOps

#build site filename
destination: public

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - gearsofgordon.md
      - fencinghubacademy.md
      - weddingbook.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
